#!/usr/bin/env node
// Work hours against the monthly target, and the program/project timeline (Constitution §2), from the ledger.
//
//   node tools/hours.mjs                print the summary (Markdown)
//   node tools/hours.mjs --write-state  also refresh the "Hours" block in STATE.md
//
// Definitions:
// - Work hours = active_min of ledger entries with kind `work` or `reconstructed`. Setup/admin sessions and
//   gaps are reported separately and do not count.
// - An entry belongs to the calendar month (Asia/Shanghai) of its open_utc.
// - Program start = the date of the first `work` entry; program end = start + 12 months. "+N months" is calendar
//   arithmetic clamped to month end. A month's target is TARGET_HOURS pro-rated by its days inside the program.
// - Project kickoff = the date of the project's first work entry; earliest close = kickoff + 2 months;
//   latest close = min(kickoff + 3 months, program end).
// - Expected project hours = TARGET_HOURS per 30.44 days since kickoff; flagged below SHORTFALL after 14 days.
//   Keep TARGET_HOURS and SHORTFALL in sync with playbook/defaults.md.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const TARGET_HOURS = 60;
const SHORTFALL = 0.6;
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const LEDGER = path.join(ROOT, 'history', 'ledger.jsonl');
const STATE = path.join(ROOT, 'STATE.md');
const SH = 8 * 3600e3; // Asia/Shanghai offset (no DST)
const DAY = 86400e3;

// Closed projects stop accruing expected hours at their `closed` date (repos.json, set at P5).
const BOM_RE = new RegExp('^' + String.fromCharCode(0xfeff));
const REG = path.join(ROOT, 'repos.json');
const closedOn = new Map((fs.existsSync(REG) ? JSON.parse(fs.readFileSync(REG, 'utf8').replace(BOM_RE, '')).repos : [])
  .filter(r => r.closed).map(r => [r.key, r.closed]));
const entries = fs.existsSync(LEDGER)
  ? fs.readFileSync(LEDGER, 'utf8').split(/\r?\n/).filter(Boolean).map(l => JSON.parse(l)) : [];
const isWork = e => e.kind === 'work' || e.kind === 'reconstructed';
const shDate = t => new Date(t + SH).toISOString().slice(0, 10);          // YYYY-MM-DD in Asia/Shanghai
const midnight = d => Date.parse(`${d}T00:00:00+08:00`);                  // Shanghai midnight, epoch ms
const h = min => Math.round(min / 6) / 10;                                 // minutes -> hours, 1 decimal
const pad = n => String(n).padStart(2, '0');
function addMonths(d, n) {
  let [y, m, day] = d.split('-').map(Number);
  m += n; y += Math.floor((m - 1) / 12); m = ((m - 1) % 12 + 12) % 12 + 1;
  const last = new Date(Date.UTC(y, m, 0)).getUTCDate();
  return `${y}-${pad(m)}-${pad(Math.min(day, last))}`;
}
const now = Date.now();
const today = shDate(now);

const work = entries.filter(isWork);
const other = entries.filter(e => !isWork(e));
const lines = [];
lines.push(`<!-- hours:start -->`);
lines.push(`_Generated by \`node tools/hours.mjs\` at ${new Date(now).toISOString()}. Work hours = active time of work sessions; target ${TARGET_HOURS} h per calendar month (Asia/Shanghai)._`);
lines.push('');

if (!work.length) {
  lines.push('No work sessions yet. The program starts at the first `start work`; the monthly target applies from then.');
} else {
  const startD = shDate(Date.parse(work[0].open_utc)), endD = addMonths(startD, 12);
  const start = midnight(startD), end = midnight(endD);
  lines.push(`**Program**: ${startD} → ${endD} (today ${today}, day ${Math.floor((midnight(today) - start) / DAY) + 1}).`);
  lines.push('');

  const byMonth = new Map();
  for (const e of work) {
    const m = shDate(Date.parse(e.open_utc)).slice(0, 7);
    const x = byMonth.get(m) ?? { min: 0, n: 0 };
    x.min += e.active_min ?? 0; x.n++; byMonth.set(m, x);
  }
  lines.push('| Month | Work sessions | Work hours | Month target | Status |');
  lines.push('|---|---|---|---|---|');
  const last = shDate(Math.min(now, end - 1)).slice(0, 7);
  for (let m = startD.slice(0, 7); m <= last; m = addMonths(`${m}-01`, 1).slice(0, 7)) {
    const mStart = midnight(`${m}-01`), mEnd = midnight(addMonths(`${m}-01`, 1));
    const days = (mEnd - mStart) / DAY;
    const target = TARGET_HOURS * (Math.min(mEnd, end) - Math.max(mStart, start)) / DAY / days;
    const x = byMonth.get(m) ?? { min: 0, n: 0 };
    let status;
    if (now < mEnd) {
      const soFar = TARGET_HOURS * Math.max(0, (Math.min(now, end) - Math.max(mStart, start)) / DAY) / days;
      const diff = h(x.min) - soFar;
      status = `${diff >= 0 ? 'ahead' : 'behind'} by ${Math.abs(diff).toFixed(1)} h (pro-rata to date ${soFar.toFixed(1)} h)`;
    } else status = h(x.min) >= target ? 'met' : `missed by ${(target - h(x.min)).toFixed(1)} h`;
    lines.push(`| ${m} | ${x.n} | ${h(x.min).toFixed(1)} | ${target.toFixed(1)} | ${status} |`);
  }
  lines.push('');

  const byProject = new Map();
  for (const e of work) {
    const k = e.project ?? 'unassigned';
    const x = byProject.get(k) ?? { min: 0, n: 0, kickoff: shDate(Date.parse(e.open_utc)), phases: {} };
    x.min += e.active_min ?? 0; x.n++;
    x.phases[e.phase ?? '?'] = (x.phases[e.phase ?? '?'] ?? 0) + (e.active_min ?? 0);
    byProject.set(k, x);
  }
  lines.push('| Project | Kickoff | Day | Earliest close | Latest close | Work sessions | Work hours (by phase) | Expected to date | Ratio |');
  lines.push('|---|---|---|---|---|---|---|---|---|');
  for (const [k, x] of byProject) {
    const ks = midnight(x.kickoff);
    const earliest = addMonths(x.kickoff, 2);
    const latest = [addMonths(x.kickoff, 3), endD].sort()[0];
    const closed = closedOn.get(k);
    const upto = closed ? midnight(closed) : now;
    const expected = TARGET_HOURS * (upto - ks) / (30.44 * DAY);
    const ratio = expected > 0 ? h(x.min) / expected : 1;
    // Flag only after 14 days; earlier ratios are dominated by noise (e.g., day 1).
    const flag = ratio < SHORTFALL && upto - ks >= 14 * DAY ? ' (below 60 %)' : '';
    const day = closed ? `closed ${closed}` : String(Math.floor((midnight(today) - ks) / DAY) + 1);
    const byPhase = Object.entries(x.phases).sort().map(([p, m]) => `${p} ${h(m).toFixed(1)}`).join(', ');
    lines.push(`| ${k} | ${x.kickoff} | ${day} | ${earliest} | ${latest} | ${x.n} | ${h(x.min).toFixed(1)} (${byPhase}) | ${expected.toFixed(1)} | ${(ratio * 100).toFixed(0)} %${flag} |`);
  }
}
lines.push('');
lines.push(`Not counted: ${other.length} setup/admin/gap entries, ${h(other.reduce((n, e) => n + (e.active_min ?? 0), 0)).toFixed(1)} active hours.`);
lines.push(`<!-- hours:end -->`);
const block = lines.join('\n');
console.log(block);

if (process.argv.includes('--write-state')) {
  const s = fs.readFileSync(STATE, 'utf8');
  const re = /<!-- hours:start -->[\s\S]*?<!-- hours:end -->/;
  if (!re.test(s)) { console.error('STATE.md has no hours block'); process.exit(1); }
  fs.writeFileSync(STATE, s.replace(re, () => block));
}
