#!/usr/bin/env node
// Work hours against the monthly target (Constitution §2), computed from history/ledger.jsonl.
//
//   node tools/hours.mjs                print the summary (Markdown)
//   node tools/hours.mjs --write-state  also refresh the "Hours" block in STATE.md
//
// Definitions:
// - Work hours = active_min of ledger entries with kind `work` or `reconstructed`. Setup/admin sessions and
//   gaps are reported separately and do not count.
// - An entry belongs to the calendar month (Asia/Shanghai) of its open_utc.
// - The program starts at the first `work` entry and lasts 12 months. A month's target is TARGET_HOURS,
//   pro-rated by the share of its days inside the program.
// - Month to date: the target pro-rated to today; "behind" means below it.
// - Per project: expected hours = TARGET_HOURS per 30.44 days since the project's first work entry.
//   Keep TARGET_HOURS and SHORTFALL in sync with playbook/defaults.md.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const TARGET_HOURS = 60;
const SHORTFALL = 0.6; // project flagged below 60 % of expected hours
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const LEDGER = path.join(ROOT, 'history', 'ledger.jsonl');
const STATE = path.join(ROOT, 'STATE.md');
const SH = 8 * 3600e3; // Asia/Shanghai offset (no DST)
const DAY = 86400e3;

const entries = fs.existsSync(LEDGER)
  ? fs.readFileSync(LEDGER, 'utf8').split(/\r?\n/).filter(Boolean).map(l => JSON.parse(l)) : [];
const isWork = e => e.kind === 'work' || e.kind === 'reconstructed';
const shDate = t => new Date(t + SH).toISOString().slice(0, 10);   // YYYY-MM-DD in Asia/Shanghai
const month = t => shDate(t).slice(0, 7);
const h = min => Math.round(min / 6) / 10;                          // minutes -> hours, 1 decimal
const now = Date.now();

const work = entries.filter(isWork);
const other = entries.filter(e => !isWork(e));
const lines = [];
lines.push(`<!-- hours:start -->`);
lines.push(`_Generated by \`node tools/hours.mjs\` at ${new Date(now).toISOString()}. Work hours = active time of work sessions; target ${TARGET_HOURS} h per calendar month (Asia/Shanghai)._`);
lines.push('');

if (!work.length) {
  lines.push('No work sessions yet. The monthly target applies from the program start (the first `start work`).');
} else {
  const start = Date.parse(shDate(Date.parse(work[0].open_utc)) + 'T00:00:00+08:00');
  const endD = new Date(start + SH); endD.setUTCMonth(endD.getUTCMonth() + 12);
  const end = endD.getTime() - SH; // program end (exclusive), Shanghai midnight
  const byMonth = new Map();
  for (const e of work) {
    const m = month(Date.parse(e.open_utc));
    const x = byMonth.get(m) ?? { min: 0, n: 0 };
    x.min += e.active_min ?? 0; x.n++; byMonth.set(m, x);
  }
  // Every month from program start to the current month (or program end).
  lines.push('| Month | Work sessions | Work hours | Month target | Month to date |');
  lines.push('|---|---|---|---|---|');
  const cur = month(Math.min(now, end - 1));
  for (let m = month(start); m <= cur; ) {
    const [y, mo] = m.split('-').map(Number);
    const mStart = Date.parse(`${m}-01T00:00:00+08:00`);
    const mEnd = Date.parse(`${mo === 12 ? y + 1 : y}-${String(mo === 12 ? 1 : mo + 1).padStart(2, '0')}-01T00:00:00+08:00`);
    const days = (mEnd - mStart) / DAY;
    const inDays = (Math.min(mEnd, end) - Math.max(mStart, start)) / DAY;
    const target = TARGET_HOURS * inDays / days;
    const x = byMonth.get(m) ?? { min: 0, n: 0 };
    let mtd = 'closed';
    if (now < mEnd) {
      const soFar = TARGET_HOURS * Math.max(0, (Math.min(now, end) - Math.max(mStart, start)) / DAY) / days;
      const diff = h(x.min) - soFar;
      mtd = `${diff >= 0 ? 'ahead' : 'behind'} by ${Math.abs(diff).toFixed(1)} h (pro-rata ${soFar.toFixed(1)} h)`;
    } else mtd = h(x.min) >= target ? 'met' : `missed by ${(target - h(x.min)).toFixed(1)} h`;
    lines.push(`| ${m} | ${x.n} | ${h(x.min).toFixed(1)} | ${target.toFixed(1)} | ${mtd} |`);
    m = `${mo === 12 ? y + 1 : y}-${String(mo === 12 ? 1 : mo + 1).padStart(2, '0')}`;
  }
  lines.push('');
  const byProject = new Map();
  for (const e of work) {
    const k = e.project ?? 'unassigned';
    const x = byProject.get(k) ?? { min: 0, n: 0, first: Date.parse(e.open_utc) };
    x.min += e.active_min ?? 0; x.n++; byProject.set(k, x);
  }
  lines.push('| Project | Work sessions | Work hours | First session | Expected to date | Ratio |');
  lines.push('|---|---|---|---|---|---|');
  for (const [k, x] of byProject) {
    const expected = TARGET_HOURS * (now - x.first) / (30.44 * DAY);
    const ratio = expected > 0 ? h(x.min) / expected : 1;
    lines.push(`| ${k} | ${x.n} | ${h(x.min).toFixed(1)} | ${shDate(x.first)} | ${expected.toFixed(1)} | ${(ratio * 100).toFixed(0)} %${ratio < SHORTFALL ? ' (shortfall)' : ''} |`);
  }
}
lines.push('');
lines.push(`Not counted: ${other.length} setup/admin/gap entries, ${h(other.reduce((n, e) => n + (e.active_min ?? 0), 0)).toFixed(1)} active hours.`);
lines.push(`<!-- hours:end -->`);
const block = lines.join('\n');
console.log(block);

if (process.argv.includes('--write-state')) {
  const s = fs.readFileSync(STATE, 'utf8');
  const re = /<!-- hours:start -->[\s\S]*?<!-- hours:end -->/;
  if (!re.test(s)) { console.error('STATE.md has no hours block'); process.exit(1); }
  fs.writeFileSync(STATE, s.replace(re, () => block));
}
